### ISSUE TITLE
is there any negative samples in dataset?

### ISSUE THREAD

**Issue by yzho0907** [daiquocnguyen/CapsE#2]
`
def parse_line(line):
    line = line.strip().split()
    sub = line[0]
    rel = line[1]
    obj = line[2]
    val = [1]
    if len(line) > 3:
        if line[3] == '-1':
            # print('entered')
            val = [-1]
    return sub, obj, rel, val` in train.txt there is no line list that is over 3, which means no negative samples? i am a bit confused, any idea? thx

**Comment by daiquocnguyen** [comment]
It is only for the case when a dataset consists of negative samples. You can see such datasets as WN11 and FB13 for the triple classification task.

**Comment by yzho0907** [comment]
thx, but do u mean there is no any invalid triple in FB15k237 and WN18RR during the training process?

**Comment by daiquocnguyen** [comment]
During training, invalid triples are sampled by corrupting valid triples, using the common Bernoulli
strategy. You can see this in the training protocol section in our paper.

**Comment by yzho0907** [comment]
is corrupting part in builddata_softplus.py? thx for your kind patience
