### ISSUE TITLE
dataset SEARCH17

### ISSUE THREAD

**Issue by loutkg** [daiquocnguyen/CapsE#3]
I have a project follow your work.
 I want to reproduce your results of Search personalization , but I cannot find the dataset SEARCH17.
Would that be possible to share this data?!
I would really appreciate if you can help me,

**Comment by daiquocnguyen** [comment]
You should contact the second author to get the SEARCH17 dataset.

**Comment by daiquocnguyen** [comment]
Hi, SEARCH17 is released as I get an agreement from the second author.
