### ISSUE TITLE
Can not achieve model-50.eval.0.txt document

### ISSUE THREAD

**Issue by Qining1231** [daiquocnguyen/CapsE#4]
Hi,
I type the command:
$ python CapsE.py --embedding_dim 100 --num_epochs 31 --num_filters 50 --learning_rate 0.0001 --name FB15k-237 --useConstantInit --savedEpochs 30 --model_name fb15k237
But I did not achieve .txt docoments, like model-50.eval.0.txt, model-50.eval.1.txt,...,model-50.eval.7
.txt.(These txt documents are needed when executing eval.py )
Is there any problem with CapsE.py?

BTW, I have the same problem with ConvKB.

**Comment by daiquocnguyen** [comment]
You can see the "Evaluation metrics" section in README.

**Comment by 1780041410** [comment]
> Hi,
> I type the command:
> $ python CapsE.py --embedding_dim 100 --num_epochs 31 --num_filters 50 --learning_rate 0.0001 --name FB15k-237 --useConstantInit --savedEpochs 30 --model_name fb15k237
> But I did not achieve .txt docoments, like model-50.eval.0.txt, model-50.eval.1.txt,...,model-50.eval.7
> .txt.(These txt documents are needed when executing eval.py )
> Is there any problem with CapsE.py?
> 
> BTW, I have the same problem with ConvKB.

i have same question ,could you help me

**Comment by 1780041410** [comment]
my mail :1780041410@qq.com

**Comment by Qining1231** [comment]
> You can see the "Evaluation metrics" section in README.

the CapsE.py do not save the .txt docoments, like model-50.eval.0.txt, model-50.eval.1.txt,...,model-50.eval.7.txt.

**Comment by daiquocnguyen** [comment]
You can see examples in command.sh

**Comment by Qining1231** [comment]
> You can see examples in command.sh

Problem solved! Thank you
