### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by 1780041410** [daiquocnguyen/CapsE#5]
hello ,when i run the follow ,some question caused.
![image](https://user-images.githubusercontent.com/32005041/59159013-1b880e00-8af6-11e9-9593-4e6ddfd6dc8f.png)

**Comment by 1780041410** [comment]
could you help me ? thanks

**Comment by 1780041410** [comment]
the first is  python CapsE.py --embedding_dim 100 --num_epochs 31 --num_filters 50 --learning_rate 0.0001 --name FB15k-237 --useConstantInit --savedEpochs 30 --model_name fb15k237

the seccond is(the above picture ) python evalCapsE.py --embedding_dim 100 --num_filters 50 --name FB15k-237 --useConstantInit --model_index 30 --model_name fb15k237 --num_splits 8 --decode

**Comment by datquocnguyen** [comment]
See: https://github.com/daiquocnguyen/CapsE/blob/master/command.sh 
You have to run commands in [`command.sh`](https://github.com/daiquocnguyen/CapsE/blob/master/command.sh) before running `python evalCapsE.py --embedding_dim 100 --num_filters 50 --name FB15k-237 --useConstantInit --model_index 30 --model_name fb15k237 --num_splits 8 --decode`

**Comment by zysforever** [comment]
> See: https://github.com/daiquocnguyen/CapsE/blob/master/command.sh
> You have to run commands in [`command.sh`](https://github.com/daiquocnguyen/CapsE/blob/master/command.sh) before running `python evalCapsE.py --embedding_dim 100 --num_filters 50 --name FB15k-237 --useConstantInit --model_index 30 --model_name fb15k237 --num_splits 8 --decode`

After I run  `python CapsE.py --embedding_dim 100 --num_epochs 31 --num_filters 50 --learning_rate 0.0001 --name FB15k-237 --useConstantInit --savedEpochs 30 --model_name fb15k237,` should I run the `python evalCapsE.py --embedding_dim 100 --num_filters 50 --name FB15k-237 --useConstantInit --model_index 30 --model_name fb15k237 --num_splits 8 --testIdx 0` each time until testIdx 7 ? Then run `python evalCapsE.py --embedding_dim 100 --num_filters 50 --name FB15k-237 --useConstantInit --model_index 30 --model_name fb15k237 --num_splits 8 --decode` for the final results. Am I right to do like this? Looking forward to your reply.
