### ISSUE TITLE
FileNotFoundError: [Errno 2] 

### ISSUE THREAD

**Issue by Bryan2Chow** [daiquocnguyen/CapsE#6]
![image](https://user-images.githubusercontent.com/42020225/60967958-82475400-a34e-11e9-9c23-7e7d2280dc95.png)
执行 Evaluation metrics 提示未能找到model-30.eval.0.txt 查看文件夹发现 training后只生成3个非txt文件   请问  model-30.eval.X.txt 文件是通过哪一步操作生成的    初学者   还请指点  多谢！

**Comment by daiquocnguyen** [comment]
I can not read Chinese.

**Comment by zysforever** [comment]
> I can not read Chinese.

After I run the training commond, I found that only three non txt files were generated, and no model-20.eval.X.txt was generated. So I'd like to know how can I generate the txt files. I'm a novice and need your help. Looking forward to your reply. Thank you very much!
