### ISSUE TITLE
'CapsE' object has no attribute 'dropout_keep_prob'

### ISSUE THREAD

**Issue by By-he** [daiquocnguyen/CapsE#9]
Hello, first of all, thank you very much for your help in my field of study, but in the process of interpreting the code, when running CapsE_SEARCH17.py, it shows 'CapsE' object has no attribute 'dropout_keep_prob' Question, as a novice, I am very difficult to solve this problem, I hope the author can help, I look forward to your reply, thank you.

**Comment by daiquocnguyen** [comment]
You can delete the line 125.
